name: Auto deploy
run-name: Auto deploy

on:
  pull_request:
   types:
     - closed
  # push:
  #   branches:
  #     - staging

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'automerge')

    name: Build and deploy to GH Pages

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
    
    permissions:
      pages: write

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: ivan@codemain.pro
          build_dir: dist
          branch: staging
          commit_message: Auto deploying to GitHub Pages!